[tools]
bun = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:giallo-kak" = "latest"
"github:BurntSushi/ripgrep" = "latest"
"github:LargeModGames/spotatui" = "latest"
"github:bjarneo/cliamp" = "latest"
"github:chenyukang/ghr" = "latest"
"github:chojs23/concord" = "2.5.13"
"github:gammons/slk" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:modem-dev/hunk" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
"npm:@opencode-ai/cli" = "next"
"npm:druk" = "latest"
"npm:opencode-ai" = "latest"
"npm:t3" = { version = "nightly", trust_policy_excludes = ["@pierre/theme@1.1.0"] }

[settings]
idiomatic_version_file_enable_tools = ["node"]
auto_update = true
