# fish completion for omp — generated by `omp completions fish`

function __fish_omp_no_subcommand
	for i in (commandline -opc)
		if contains -- $i acp agents auth-broker auth-gateway bench commit completions config dry-balance gallery gc grep grievances install join models plugin read say search q setup shell ssh stats tiny-models token ttsr update usage worktree wt
			return 1
		end
	end
	return 0
end

complete -c omp -f -n '__fish_omp_no_subcommand' -a 'acp' -d 'Run Oh My Pi as an ACP (Agent Client Protocol) server over stdio'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'agents' -d 'Manage bundled task agents'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'auth-broker' -d 'Manage the omp auth-broker (credential vault)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'auth-gateway' -d 'Run an auth-gateway forward proxy backed by the configured broker'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'bench' -d 'Benchmark models with the same prompt: time-to-first-token and generation throughput (tokens/s)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'commit' -d 'Generate a commit message and update changelogs'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'completions' -d 'Print a shell completion script (bash, zsh, or fish)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'config' -d 'Manage configuration settings'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'dry-balance' -d 'Dry-run OAuth account balancing across random session ids'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'gallery' -d 'Preview tool renderers across streaming, in-progress, success, and failure states'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'gc' -d 'Run storage garbage collection'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'grep' -d 'Test grep tool'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'grievances' -d 'View, clean, or push reported tool issues (auto-QA grievances)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'install' -d 'Install or link an extension package (alias of `plugin install`/`plugin link`)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'join' -d 'Join a shared collab session (same as /join)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'models' -d 'List, search, and refresh available models'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'plugin' -d 'Manage plugins (install, uninstall, list, etc.)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'read' -d 'Show what the read tool will return for a path, URL, or internal URI'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'say' -d 'Synthesize text with the local TTS engine and play it through the speakers'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'search' -d 'Test web search providers'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'q' -d 'Test web search providers'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'setup' -d 'Run onboarding setup or install dependencies for optional features'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'shell' -d 'Interactive shell console'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'ssh' -d 'Manage SSH host configurations'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'stats' -d 'View usage statistics'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'tiny-models' -d 'Download tiny local models (session titles + memory)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'token' -d 'Get the API key or OAuth token for a provider'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'ttsr' -d 'Inspect and test Time-Traveling Stream Rules (TTSR)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'update' -d 'Check for and install updates'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'usage' -d 'Show provider usage limits for every authenticated account'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'worktree' -d 'List or clear agent-managed git worktrees (~/.omp/wt)'
complete -c omp -f -n '__fish_omp_no_subcommand' -a 'wt' -d 'List or clear agent-managed git worktrees (~/.omp/wt)'

complete -c omp -n '__fish_omp_no_subcommand' -l model -d 'Model to use (fuzzy match: "opus", "gpt-5.2", or "openai/gpt-5.2")' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l smol -d 'Smol/fast model for lightweight tasks (or PI_SMOL_MODEL env)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l slow -d 'Slow/reasoning model for thorough analysis (or PI_SLOW_MODEL env)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l plan -d 'Plan model for architectural planning (or PI_PLAN_MODEL env)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l provider -d 'Provider to use (legacy; prefer --model)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l api-key -d 'API key (defaults to env vars)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l system-prompt -d 'System prompt (default: coding assistant prompt)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l append-system-prompt -d 'Append text or file contents to the system prompt' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l allow-home -d 'Allow starting in ~ without auto-switching to a temp dir'
complete -c omp -n '__fish_omp_no_subcommand' -l profile -d 'Use an isolated profile for auth, sessions, settings, and caches' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l alias -d 'Create a shell shortcut for the selected profile and exit' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l cwd -d 'Directory to start in (overrides the launch cwd)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l mode -d 'Output mode: text (default), json, rpc, or rpc-ui' -x -a 'text json rpc acp rpc-ui'
complete -c omp -n '__fish_omp_no_subcommand' -l config -d 'Load an extra config.yml-style overlay for this run (repeatable)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -s p -l print -d 'Non-interactive mode: process prompt and exit'
complete -c omp -n '__fish_omp_no_subcommand' -s c -l continue -d 'Continue previous session'
complete -c omp -n '__fish_omp_no_subcommand' -s r -l resume -d 'Resume a session (by ID prefix, path, or picker if omitted)' -x -a '(command omp __complete sessions -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l session-dir -d 'Directory for session storage and lookup' -x -a '(__fish_complete_directories (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l no-session -d 'Don’t save session (ephemeral)'
complete -c omp -n '__fish_omp_no_subcommand' -l models -d 'Comma-separated model patterns for Ctrl+P cycling' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_omp_no_subcommand' -l no-tools -d 'Disable all built-in tools'
complete -c omp -n '__fish_omp_no_subcommand' -l no-lsp -d 'Disable LSP tools, formatting, and diagnostics'
complete -c omp -n '__fish_omp_no_subcommand' -l no-pty -d 'Disable PTY-based interactive bash execution'
complete -c omp -n '__fish_omp_no_subcommand' -l tools -d 'Comma-separated list of tools to enable (default: all)' -x -a 'read bash edit ast_grep ast_edit ask debug eval ssh github glob grep lsp inspect_image browser checkpoint rewind task job irc todo web_search search_tool_bm25 write memory_edit retain recall reflect learn manage_skill'
complete -c omp -n '__fish_omp_no_subcommand' -l thinking -d 'Set thinking level: off, minimal, low, medium, high, xhigh, max, auto' -x -a 'off minimal low medium high xhigh max auto'
complete -c omp -n '__fish_omp_no_subcommand' -l hide-thinking -d 'Hide thinking blocks in TUI output (display only, does not disable model thinking)'
complete -c omp -n '__fish_omp_no_subcommand' -l advisor -d 'Enable the advisor runtime (passively reviews each turn and injects notes)'
complete -c omp -n '__fish_omp_no_subcommand' -l hook -d 'Load a hook/extension file (can be used multiple times)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -s e -l extension -d 'Load an extension file (can be used multiple times)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l no-extensions -d 'Disable extension discovery (explicit -e paths still work)'
complete -c omp -n '__fish_omp_no_subcommand' -l no-skills -d 'Disable skills discovery and loading'
complete -c omp -n '__fish_omp_no_subcommand' -l skills -d 'Comma-separated glob patterns to filter skills (e.g., git-*,docker)' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l no-rules -d 'Disable rules discovery and loading'
complete -c omp -n '__fish_omp_no_subcommand' -l export -d 'Export session file to HTML and exit' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l no-title -d 'Disable title auto-generation'
complete -c omp -n '__fish_omp_no_subcommand' -l print-thoughts -d 'Include thinking blocks in print mode text output'
complete -c omp -n '__fish_omp_no_subcommand' -l max-time -d 'Stop the session after this many seconds' -r -F
complete -c omp -n '__fish_omp_no_subcommand' -l auto-approve -d 'Auto-approve all tool calls (skip approval prompts)'
complete -c omp -n '__fish_omp_no_subcommand' -l approval-mode -d 'Override tools.approvalMode for this session (always-ask|write|yolo)' -x -a 'always-ask write yolo'

complete -c omp -n '__fish_seen_subcommand_from agents' -s f -l force -d 'Overwrite existing agent files'
complete -c omp -n '__fish_seen_subcommand_from agents' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from agents' -l dir -d 'Output directory (overrides --user/--project)' -r -F
complete -c omp -n '__fish_seen_subcommand_from agents' -l user -d 'Write to ~/.omp/agent/agents (default)'
complete -c omp -n '__fish_seen_subcommand_from agents' -l project -d 'Write to ./.omp/agents'
complete -c omp -f -n '__fish_seen_subcommand_from agents' -a 'unpack' -d 'Agents action'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -s b -l bind -d 'Bind address for `serve` (host:port)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l regenerate -d 'Regenerate the bearer token'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l via -d 'SSH user@host for remote login (login --via=user@host)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l provider -d 'Override provider id for `import` (e.g. when JSON `type` is unrecognized)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l include-disabled -d 'Import credentials whose JSON has `disabled: true` (import)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l from-local -d 'migrate source: local SQLite + env vars (required for `migrate`)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l include-env -d 'Capture env-var API keys for providers not yet on broker (migrate)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l include-oauth -d 'Also upload OAuth from local SQLite during migrate (default skips them)'
complete -c omp -n '__fish_seen_subcommand_from auth-broker' -l dry-run -d 'Print actions without executing (import / login --via / migrate)'
complete -c omp -f -n '__fish_seen_subcommand_from auth-broker' -a 'serve token login logout import migrate status list' -d 'Sub-command'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l json -d 'Output JSON (token/status/check)'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -s b -l bind -d 'Bind address for `serve` (host:port)' -r -F
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l regenerate -d 'Regenerate the gateway bearer token (token)'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l no-auth -d 'Disable inbound bearer-token auth (serve). Useful when bound to loopback — any caller is allowed.'
complete -c omp -n '__fish_seen_subcommand_from auth-gateway' -l strict -d 'For `check`: additionally probe each credential against its provider’s chat-completion endpoint. Slower; consumes a tiny amount of quota per credential.'
complete -c omp -f -n '__fish_seen_subcommand_from auth-gateway' -a 'serve token status check' -d 'Sub-command'
complete -c omp -n '__fish_seen_subcommand_from bench' -l runs -d 'Requests per model (results are averaged)' -x
complete -c omp -n '__fish_seen_subcommand_from bench' -l max-tokens -d 'Max output tokens per request' -x
complete -c omp -n '__fish_seen_subcommand_from bench' -l prompt -d 'Custom prompt text (default: bundled bench prompt)' -r -F
complete -c omp -n '__fish_seen_subcommand_from bench' -l service-tier -d 'Service tier applied per model family (default: configured `tier.*` settings; `none` omits it)' -x -a 'none auto default flex scale priority'
complete -c omp -n '__fish_seen_subcommand_from bench' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from bench' -l par -d 'Execute runs with N parallel queries/requests' -x
complete -c omp -F -n '__fish_seen_subcommand_from bench'
complete -c omp -n '__fish_seen_subcommand_from commit' -l push -d 'Push after committing'
complete -c omp -n '__fish_seen_subcommand_from commit' -l dry-run -d 'Preview without committing'
complete -c omp -n '__fish_seen_subcommand_from commit' -l no-changelog -d 'Skip changelog updates'
complete -c omp -n '__fish_seen_subcommand_from commit' -l legacy -d 'Use legacy deterministic pipeline'
complete -c omp -n '__fish_seen_subcommand_from commit' -s c -l context -d 'Additional context for the model' -r -F
complete -c omp -n '__fish_seen_subcommand_from commit' -s m -l model -d 'Override model selection' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -f -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish' -d 'Target shell'
complete -c omp -n '__fish_seen_subcommand_from config' -l json -d 'Output JSON'
complete -c omp -f -n '__fish_seen_subcommand_from config' -a 'list get set reset path init-xdg' -d 'Config action'
complete -c omp -n '__fish_seen_subcommand_from dry-balance' -l model -d 'Model selector (same syntax as --model on omp)' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_seen_subcommand_from dry-balance' -l count -d 'Number of random session ids to try' -x
complete -c omp -n '__fish_seen_subcommand_from dry-balance' -l concurrency -d 'Maximum concurrent credential resolutions' -x
complete -c omp -n '__fish_seen_subcommand_from dry-balance' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from dry-balance' -l bench -d 'Send one live benchmark request per OAuth account'
complete -c omp -F -n '__fish_seen_subcommand_from dry-balance'
complete -c omp -n '__fish_seen_subcommand_from gallery' -s t -l tool -d 'Render a single tool by name' -r -F
complete -c omp -n '__fish_seen_subcommand_from gallery' -s s -l state -d 'Render only the given lifecycle state(s)' -x -a 'streaming streaming args progress in progress success done error failed'
complete -c omp -n '__fish_seen_subcommand_from gallery' -s w -l width -d 'Render width in columns' -x
complete -c omp -n '__fish_seen_subcommand_from gallery' -s e -l expanded -d 'Render the expanded variant of each renderer'
complete -c omp -n '__fish_seen_subcommand_from gallery' -l plain -d 'Strip ANSI styling from the output'
complete -c omp -n '__fish_seen_subcommand_from gallery' -l screenshot -d 'Capture the rendered output as PNG screenshot(s) via VHS instead of printing ANSI (requires vhs)'
complete -c omp -n '__fish_seen_subcommand_from gallery' -s o -l out -d 'Screenshot output path (with --screenshot); suffixed per image when split across multiple' -r -F
complete -c omp -n '__fish_seen_subcommand_from gallery' -l font -d 'Screenshot font family (default: JetBrainsMono Nerd Font)' -r -F
complete -c omp -n '__fish_seen_subcommand_from gallery' -l font-size -d 'Screenshot font size in points (default: 18)' -x
complete -c omp -n '__fish_seen_subcommand_from gc' -l apply -d 'Apply changes (default is dry-run)'
complete -c omp -n '__fish_seen_subcommand_from gc' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from gc' -l agent-dir -d 'Agent directory to maintain' -r -F
complete -c omp -n '__fish_seen_subcommand_from gc' -l blobs -d 'Sweep unreferenced blobs'
complete -c omp -n '__fish_seen_subcommand_from gc' -l archive -d 'Archive cold sessions'
complete -c omp -n '__fish_seen_subcommand_from gc' -l wal -d 'Checkpoint history/model database WAL files'
complete -c omp -n '__fish_seen_subcommand_from gc' -l cold-archive-after-days -d 'Minimum session age before archiving' -x
complete -c omp -n '__fish_seen_subcommand_from gc' -l retain-newest-global -d 'Always keep this many newest sessions active' -x
complete -c omp -n '__fish_seen_subcommand_from gc' -l retain-newest-per-cwd -d 'Always keep this many newest sessions per cwd active' -x
complete -c omp -n '__fish_seen_subcommand_from grep' -s g -l glob -d 'Filter files by glob pattern' -r -F
complete -c omp -n '__fish_seen_subcommand_from grep' -s l -l limit -d 'Max matches' -x
complete -c omp -n '__fish_seen_subcommand_from grep' -s C -l context -d 'Context lines' -x
complete -c omp -n '__fish_seen_subcommand_from grep' -s f -l files -d 'Output file names only'
complete -c omp -n '__fish_seen_subcommand_from grep' -s c -l count -d 'Output match counts per file'
complete -c omp -n '__fish_seen_subcommand_from grep' -l no-gitignore -d 'Include files excluded by .gitignore'
complete -c omp -F -n '__fish_seen_subcommand_from grep'
complete -c omp -n '__fish_seen_subcommand_from grievances' -s n -l limit -d 'Number of recent issues to show (list)' -x
complete -c omp -n '__fish_seen_subcommand_from grievances' -s t -l tool -d 'Filter by tool name (list, clean)' -r -F
complete -c omp -n '__fish_seen_subcommand_from grievances' -s j -l json -d 'Output as JSON'
complete -c omp -n '__fish_seen_subcommand_from grievances' -l id -d 'Delete a single grievance by id (clean)' -x
complete -c omp -n '__fish_seen_subcommand_from grievances' -l all -d 'Delete every grievance (clean)'
complete -c omp -f -n '__fish_seen_subcommand_from grievances' -a 'list clean push' -d 'list (default), clean, or push'
complete -c omp -n '__fish_seen_subcommand_from install' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from install' -l force -d 'Force install'
complete -c omp -n '__fish_seen_subcommand_from install' -l dry-run -d 'Show actions without applying changes'
complete -c omp -n '__fish_seen_subcommand_from install' -l scope -d 'Install scope: "user" (default) or "project" (marketplace installs only)' -x -a 'user project'
complete -c omp -F -n '__fish_seen_subcommand_from install'
complete -c omp -F -n '__fish_seen_subcommand_from join'
complete -c omp -n '__fish_seen_subcommand_from models' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from models' -s e -l extension -d 'Load an extension file before listing (repeatable)' -r -F
complete -c omp -n '__fish_seen_subcommand_from models' -l no-extensions -d 'Disable extension discovery (explicit -e paths still work)'
complete -c omp -n '__fish_seen_subcommand_from models' -l config -d 'Load an extra config.yml-style overlay for this run (repeatable)' -r -F
complete -c omp -F -n '__fish_seen_subcommand_from models'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l fix -d 'Attempt to fix issues (doctor)'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l force -d 'Force install'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l dry-run -d 'Show actions without applying changes'
complete -c omp -n '__fish_seen_subcommand_from plugin' -s l -l local -d 'Operate on local plugin directory'
complete -c omp -n '__fish_seen_subcommand_from plugin' -l enable -d 'Enable a feature' -r -F
complete -c omp -n '__fish_seen_subcommand_from plugin' -l disable -d 'Disable a feature' -r -F
complete -c omp -n '__fish_seen_subcommand_from plugin' -l set -d 'Set plugin config (key=value)' -r -F
complete -c omp -n '__fish_seen_subcommand_from plugin' -l scope -d 'Install scope: "user" (default) or "project"' -x -a 'user project'
complete -c omp -f -n '__fish_seen_subcommand_from plugin' -a 'install uninstall list link doctor features config enable disable marketplace discover upgrade' -d 'Plugin action'
complete -c omp -F -n '__fish_seen_subcommand_from read'
complete -c omp -n '__fish_seen_subcommand_from say' -l voice -d 'Voice id' -x -a 'af_heart af_bella af_nicole af_aoede af_kore af_sarah am_michael am_fenrir am_puck bf_emma bm_george bm_fable'
complete -c omp -n '__fish_seen_subcommand_from say' -l model -d 'Local TTS model key' -x -a '(command omp __complete models -- (commandline -ct))'
complete -c omp -n '__fish_seen_subcommand_from say' -s f -l file -d 'Read the text to speak from this file' -r -F
complete -c omp -n '__fish_seen_subcommand_from say' -s o -l out -d 'Write WAV to this path instead of playing' -r -F
complete -c omp -F -n '__fish_seen_subcommand_from say'
complete -c omp -n '__fish_seen_subcommand_from search q' -l provider -d 'Search provider' -x -a 'auto perplexity gemini anthropic codex xai zai exa tinyfish jina kagi tavily firecrawl brave kimi parallel synthetic searxng startpage duckduckgo bing yahoo ecosia google mojeek public'
complete -c omp -n '__fish_seen_subcommand_from search q' -l recency -d 'Recency filter' -x -a 'day week month year'
complete -c omp -n '__fish_seen_subcommand_from search q' -s l -l limit -d 'Max results to return' -x
complete -c omp -n '__fish_seen_subcommand_from search q' -l compact -d 'Render condensed output'
complete -c omp -F -n '__fish_seen_subcommand_from search q'
complete -c omp -n '__fish_seen_subcommand_from setup' -s c -l check -d 'Check if dependencies are installed'
complete -c omp -n '__fish_seen_subcommand_from setup' -l json -d 'Output status as JSON'
complete -c omp -f -n '__fish_seen_subcommand_from setup' -a 'python speech' -d 'Optional component to install'
complete -c omp -n '__fish_seen_subcommand_from shell' -s C -l cwd -d 'Set working directory for commands' -r -F
complete -c omp -n '__fish_seen_subcommand_from shell' -s t -l timeout -d 'Timeout per command in milliseconds' -x
complete -c omp -n '__fish_seen_subcommand_from shell' -l no-snapshot -d 'Skip sourcing snapshot from user shell'
complete -c omp -n '__fish_seen_subcommand_from ssh' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from ssh' -l host -d 'Host address' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l user -d 'Username' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l port -d 'Port number' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l key -d 'Identity key path' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l desc -d 'Host description' -r -F
complete -c omp -n '__fish_seen_subcommand_from ssh' -l compat -d 'Enable compatibility mode'
complete -c omp -n '__fish_seen_subcommand_from ssh' -l scope -d 'Config scope (project|user)' -x -a 'project user'
complete -c omp -f -n '__fish_seen_subcommand_from ssh' -a 'add remove list' -d 'SSH action'
complete -c omp -n '__fish_seen_subcommand_from stats' -s p -l port -d 'Port for the dashboard server' -x
complete -c omp -n '__fish_seen_subcommand_from stats' -s j -l json -d 'Output stats as JSON'
complete -c omp -n '__fish_seen_subcommand_from stats' -s s -l summary -d 'Print summary to console'
complete -c omp -n '__fish_seen_subcommand_from tiny-models' -l json -d 'Output JSON'
complete -c omp -f -n '__fish_seen_subcommand_from tiny-models' -a 'download list' -d 'Action to perform'
complete -c omp -n '__fish_seen_subcommand_from token' -l raw -d 'Output the raw credential value without parsing nested JSON structures'
complete -c omp -n '__fish_seen_subcommand_from token' -l force-refresh -d 'Force refresh the OAuth token even if it has not expired'
complete -c omp -n '__fish_seen_subcommand_from token' -s a -l account -d 'Select the Nth OAuth account (1-based) in stored order instead of the round-robin default' -x
complete -c omp -n '__fish_seen_subcommand_from token' -s l -l list -d 'List the provider’s OAuth accounts (index + identity) and exit'
complete -c omp -F -n '__fish_seen_subcommand_from token'
complete -c omp -n '__fish_seen_subcommand_from ttsr' -l file -d 'Snippet file path, or - for stdin (ttsr test)' -r -F
complete -c omp -n '__fish_seen_subcommand_from ttsr' -s r -l rule -d 'Rule markdown file to test in isolation (skips project rule loading)' -r -F
complete -c omp -n '__fish_seen_subcommand_from ttsr' -l source -d 'Match source: text, thinking, or tool (inferred from --file when omitted)' -x -a 'text thinking tool'
complete -c omp -n '__fish_seen_subcommand_from ttsr' -l tool -d 'Tool name when source is tool (e.g. edit, write); defaults to edit' -r -F
complete -c omp -n '__fish_seen_subcommand_from ttsr' -s p -l path -d 'Candidate file path for scope/glob matching and AST language inference' -r -F
complete -c omp -n '__fish_seen_subcommand_from ttsr' -s v -l verbose -d 'Show every evaluated rule, not just triggered ones'
complete -c omp -n '__fish_seen_subcommand_from ttsr' -l json -d 'Output JSON'
complete -c omp -n '__fish_seen_subcommand_from ttsr' -l no-gitignore -d 'Include files excluded by .gitignore (ttsr scan)'
complete -c omp -n '__fish_seen_subcommand_from ttsr' -l max-bytes -d 'Maximum file size to scan in bytes; 0 disables the limit (ttsr scan)' -x
complete -c omp -f -n '__fish_seen_subcommand_from ttsr' -a 'test list scan' -d 'TTSR action'
complete -c omp -n '__fish_seen_subcommand_from update' -s f -l force -d 'Force update'
complete -c omp -n '__fish_seen_subcommand_from update' -s c -l check -d 'Check for updates without installing'
complete -c omp -n '__fish_seen_subcommand_from update' -s l -l plugins -d 'Update installed plugins'
complete -c omp -n '__fish_seen_subcommand_from usage' -s j -l json -d 'Output usage reports as JSON'
complete -c omp -n '__fish_seen_subcommand_from usage' -s p -l provider -d 'Only show usage for this provider id (e.g. anthropic)' -r -F
complete -c omp -n '__fish_seen_subcommand_from usage' -s r -l redact -d 'Redact account emails/ids (shortest unique prefix) for sharing screenshots'
complete -c omp -n '__fish_seen_subcommand_from usage' -l history -d 'Show recorded usage-limit history (hourly snapshots) instead of a live snapshot'
complete -c omp -n '__fish_seen_subcommand_from usage' -s d -l days -d 'History window in days (with --history)' -x
complete -c omp -f -n '__fish_seen_subcommand_from usage' -a 'invalidate' -d 'Optional subcommand to execute'
complete -c omp -n '__fish_seen_subcommand_from worktree wt' -l all -d 'Clear every entry, including live PR-checkout worktrees (clear)'
complete -c omp -n '__fish_seen_subcommand_from worktree wt' -s n -l dry-run -d 'Print what would be removed without touching the filesystem (clear)'
complete -c omp -n '__fish_seen_subcommand_from worktree wt' -s j -l json -d 'Emit machine-readable JSON'
complete -c omp -f -n '__fish_seen_subcommand_from worktree wt' -a 'list clear' -d 'list (default) or clear'

