"$schema" = 'https://starship.rs/config-schema.json'

format = "$custom "
right_format = ""
add_newline = false

[custom.time]
shell = "bash"
command = 'date "+%a %-l:%M %p"'
format = "[$output]($style)"
style = "fg:#475266"
when = true

[custom.battery]
shell = "bash"
command = '''
if command -v pmset &> /dev/null; then
  battery_info=$(pmset -g batt)
  percentage=$(echo "$battery_info" | grep -Eo "[0-9]+%" | cut -d% -f1)
  charging=$(echo "$battery_info" | grep -q "AC Power" && echo "1" || echo "0")

  if [ -n "$percentage" ]; then
    if [ "$percentage" -le 10 ]; then
      idx=1
    elif [ "$percentage" -le 20 ]; then
      idx=2
    elif [ "$percentage" -le 30 ]; then
      idx=3
    elif [ "$percentage" -le 40 ]; then
      idx=4
    elif [ "$percentage" -le 50 ]; then
      idx=5
    elif [ "$percentage" -le 60 ]; then
      idx=6
    elif [ "$percentage" -le 70 ]; then
      idx=7
    elif [ "$percentage" -le 80 ]; then
      idx=8
    elif [ "$percentage" -le 90 ]; then
      idx=9
    else
      idx=10
    fi

    icons_charging=("" "󰢟" "󰢜" "󰂆" "󰂇" "󰂈" "󰢝" "󰂉" "󰢞" "󰂊" "󰂅")
    icons_discharging=("" "󰂎" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂")

    if [ "$percentage" -le 10 ]; then
      color="\e[31m"
    elif [ "$percentage" -le 30 ]; then
      color="\e[33m"
    else
      if [ "$charging" = "1" ]; then
        color="\e[32m"
      else
        color="\e[37m"
      fi
    fi

    if [ "$charging" = "1" ]; then
      icon=${icons_charging[$idx]}
    else
      icon=${icons_discharging[$idx]}
    fi

    printf "%b %s%%\e[0m" "$color" "${icon} $percentage"
  fi
fi
'''
format = "$output"
when = true
