tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "aria2"
brew "bashdb"
brew "bat"
brew "boost"
brew "cmake"
brew "fish"
brew "fzf"
brew "gnupg", link: false
brew "htop"
brew "joplin"
brew "jq"
brew "mackup"
brew "mas"
brew "ncdu"
brew "neovim"
brew "pass"
brew "sqlite"
brew "pgcli"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "prettyping"
brew "pyenv"
brew "rbenv"
brew "redis", restart_service: true
brew "stow"
brew "tmux"
brew "wget"
brew "youtube-dl"
cask "caprine"
cask "clyang-welly"
cask "font-fira-code"
cask "font-hack"
cask "github"
cask "hyper"
cask "iina"
cask "keycastr"
cask "phoenix"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "spotify"
cask "squirrel"
cask "suspicious-package"
cask "webpquicklook"
cask "wireshark"
mas "Amphetamine", id: 937984704
mas "App Language Chooser", id: 451732904
mas "CotEditor", id: 1024640650
mas "Evernote", id: 406056744
mas "GIF Brewery 3", id: 1081413713
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pastebot", id: 1179623856
mas "Quip", id: 1003160018
mas "Quiver", id: 866773894
mas "Reeder", id: 880001334
mas "Simplenote", id: 692867256
mas "Spark", id: 1176895641
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
