tap "amar1729/formulae"
tap "d12frosted/emacs-plus"
tap "fish-shell/fish"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "wagoodman/dive"
brew "aria2"
brew "bashdb"
brew "bat"
brew "boost"
brew "libpng"
brew "libffi"
brew "readline"
brew "sqlite"
brew "cairo"
brew "cmake"
brew "giflib"
brew "jpeg"
brew "ffmpeg"
brew "fish"
brew "node"
brew "fx"
brew "fzf"
brew "git-lfs"
brew "gnupg", link: false
brew "hexyl"
brew "htop"
brew "imagemagick"
brew "joplin"
brew "jq"
brew "kakoune"
brew "pango"
brew "librsvg"
brew "mackup"
brew "mas"
brew "mosh"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "openldap"
brew "pass"
brew "pgcli"
brew "pinentry-mac"
brew "pipenv"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "postgresql@10"
brew "prettyping"
brew "pyenv"
brew "rbenv"
brew "redis", restart_service: true
brew "ripgrep"
brew "stow"
brew "telnet"
brew "tig"
brew "tmux"
brew "wget"
brew "wine"
brew "winetricks"
brew "youtube-dl"
brew "zlib"
brew "amar1729/formulae/browserpass"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-modern-icon"]
brew "heroku/brew/heroku"
brew "wagoodman/dive/dive"
cask "alacritty"
cask "anki"
cask "caprine"
cask "charles"
cask "clyang-welly"
cask "devdocs"
cask "flume"
cask "font-fira-code"
cask "font-hack"
cask "font-input"
cask "font-sarasa-gothic"
cask "github"
cask "hyper"
cask "iina"
cask "james"
cask "keycastr"
cask "kitty"
cask "mkchromecast"
cask "mono-mdk"
cask "mousepose"
cask "pennywise"
cask "phoenix"
cask "postman"
cask "psequel"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "sloth"
cask "soundflower"
cask "spotifree"
cask "spotify"
cask "squirrel"
cask "suspicious-package"
cask "terminus"
cask "textmate"
cask "tweeten"
cask "visual-studio-code-insiders"
cask "vivaldi"
cask "webpquicklook"
cask "wireshark"
cask "zotero"
mas "Amphetamine", id: 937984704
mas "App Language Chooser", id: 451732904
mas "CotEditor", id: 1024640650
mas "Dato", id: 1470584107
mas "Drafts", id: 1435957248
mas "Evernote", id: 406056744
mas "GIF Brewery 3", id: 1081413713
mas "Highland 2", id: 1171820258
mas "Irvue", id: 1039633667
mas "Keep It", id: 1272768911
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Mirror for Samsung TV", id: 1107644799
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pastebot", id: 1179623856
mas "Quip", id: 1003160018
mas "Quiver", id: 866773894
mas "Reeder", id: 880001334
mas "Remote Mouse", id: 403195710
mas "Simplenote", id: 692867256
mas "Spark", id: 1176895641
mas "SubEthaEdit", id: 728530824
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
