evaluate-commands %sh{
  kks init
  kak-lsp --kakoune -s $kak_session
  kak-tree-sitter -dks --init $kak_session
  gitlinker init kakoune
}

# custom modules
source "%val{config}/wakatime.kak"
source "%val{config}/wezterm.kak"
source "%val{config}/tmux.kak"
source "%val{config}/kitty.kak"
source "%val{config}/window-helper.kak"
source "%val{config}/color-highlighter.kak"
source "%val{config}/highlight.kak"
source "%val{config}/jump_mode.kak"
source "%val{config}/git.kak"
source "%val{config}/git-custom.kak"
source "%val{config}/gleam.kak"
source "%val{config}/filetypes.kak"
source "%val{config}/statusline.kak"
source "%val{config}/jk.kak"
source "%val{config}/locations.kak"
source "%val{config}/flip-boolean.kak"
source "%val{config}/lsp.kak"
source "%val{config}/yank.kak"
# source "%val{config}/reasymotion.kak"
# source "%val{config}/jump-stack.kak"
# source "%val{config}/amber.kak"

colorscheme kanagawa
# colorscheme ayu-mirage
# colorscheme catppuccin_macchiato

set global indentwidth 2
set global tabstop 2

# enable autocomplete trigger
# set global autocomplete prompt

set-option global ui_options terminal_assistant=none
set-option global scrolloff 5,5
set-option global startup_info_version 20240518

set-option global autoreload yes

set-option global grepcmd 'rg -Hn --no-heading --sort path --vimgrep'

add-highlighter global/number-lines number-lines -hlcursor -relative -separator '  '
add-highlighter global/show-whitespaces show-whitespaces -indent '▏' -lf ' ' -spc ' ' -nbsp ' ' -tab ' ' -tabpad ' '
add-highlighter global/ show-matching
add-highlighter global/ wrap -word
add-highlighter global/todo-highlighter regex //\h*(TODO:)[^\n]* 0:cyan 1:yellow,red

add-highlighter global/ regex \b(TODO|FIXME|NOTE)\b 0:default+rb

# trailing whitespaces
define-command -hidden show-trailing-whitespaces %{ try %{ add-highlighter global/trailing-whitespaces regex '\h+$' 0:default,red } }
define-command -hidden hide-trailing-whitespaces %{ try %{ remove-highlighter global/trailing-whitespaces } }
hook global WinDisplay .*              show-trailing-whitespaces
hook global ModeChange 'insert:normal' show-trailing-whitespaces
hook global ModeChange 'normal:insert' hide-trailing-whitespaces

# User mode mappings
map global user '<space>' ':kks-connect terminal-popup kks-mru<ret>'    -docstring 'recent files'
map global user n         ':e -scratch<ret>'                            -docstring 'create buffer'
map global user c         ':db<ret>'                                    -docstring 'delete buffer'
map global user q         ':q<ret>'                                     -docstring 'quit'
map global user y         ':enter-user-mode yank<ret>'                  -docstring 'yank operations'
map global user P         '!pbpaste<ret>'                               -docstring 'paste from clipboard'
map global user p         '<a-!>pbpaste<ret>'                           -docstring 'paste before from clipboard'
map global user R         '|pbpaste<ret>'                               -docstring 'replace selection with clipaboard'
map global user /         ':comment-line<ret>'                          -docstring 'comment line'
map global user ?         ':comment-block<ret>'                         -docstring 'block comment selection'
map global user e         ':open-broot<ret>'                            -docstring 'explorer'
map global user ,         ':edit-config<ret>'                           -docstring 'edit config'
map global user d         ':buffer *debug*<ret>'                        -docstring 'debug buffer'
map global user h         ':lsp-hover<ret>'                             -docstring 'lsp hover'
map global user H         ':lsp-hover-buffer<ret>'                      -docstring 'lsp hover buffer'
map global user S         ':trim-trailing-whitespaces<ret>'             -docstring 'trim trailing whitesapce'
map global user w         ':w<ret>'                                     -docstring 'write file'
map global user t         ':enter-user-mode terminal-actions<ret>'      -docstring 'terminal actions'
map global user f         ':enter-user-mode find-actions<ret>'          -docstring 'find actions'
map global user b         ':enter-user-mode buffer-actions<ret>'        -docstring 'buffer actions'
map global user B         ':enter-user-mode buffer-actions -lock<ret>'  -docstring 'buffer actions (Locked)'
map global user l         ':enter-user-mode lsp<ret>'                   -docstring 'lsp mode'

define-command trim-trailing-whitespaces -docstring 'trim trailing whitespaces' %{
  try %{
    execute-keys -draft \%s\h+$<ret>d
  }
}

define-command edit-config -docstring 'edit config' %{
  edit "%val{config}/kakrc"
}


# muscle memories from vim
map global normal <c-e> ':execute-keys vj<ret>'                  -docstring 'scroll oneline down'
map global normal <c-y> ':execute-keys vk<ret>'                  -docstring 'scroll oneline down'
map global normal <c-w> ':enter-user-mode window-actions<ret>'   -docstring 'window actions'
map global normal X     ':execute-keys xH<ret>'                  -docstring 'Select till line end'

# Move line up/down
map global normal <a-up>   'x"aZy<a-;>kPZ"azdz'
map global normal <a-down> 'xdp'

# Edit mode bash shortcuts

# Cursor movement
map global insert <c-a> <home>
map global insert <c-e> <end>
map global insert <c-b> <left>
map global insert <c-f> <right>

# Word movement
map global insert <a-b> '<esc>bhli'  # Move backward one word and return to insert mode
map global insert <a-f> '<esc>: try %{ exec El } catch %{ exec l }; exec i<ret>'

# Text manipulation
map global insert <c-w> '<esc>bc'  # Delete previous word
map global insert <c-u> '<esc><a-h>di'  # Delete from cursor to beginning of line
map global insert <c-k> '<esc><a-l>c'  # Delete from cursor to end of line
map global insert <c-h> <backspace>  # Delete previous character
map global insert <c-d> <del>      # Delete current character

# Terminal actions
declare-user-mode terminal-actions

define-command lazygit -hidden -docstring 'Launch lazygit' %{ nop %sh{
  (tsm popup lazygit &) >/dev/null 2>/dev/null
}}

define-command serpl -hidden -docstring 'Launch serpl' %{ nop %sh{
  (tsm popup serpl &) >/dev/null 2>/dev/null
}}

define-command lazyjj -hidden -docstring 'Launch lazyjj' %{ nop %sh{
  (tsm popup lazyjj &) >/dev/null 2>/dev/null
}}


define-command bottom-terminal -hidden -docstring 'Launch bottom terminal' %{
  terminal-vertical fish
}
define-command floating-terminal -hidden -docstring 'Launch floating terminal' %{ nop %sh{
  (tsm popup &) >/dev/null 2>/dev/null
}}

map global terminal-actions 'l' ':lazygit<ret>'           -docstring 'lazygit'
map global terminal-actions 'j' ':lazyjj<ret>'            -docstring 'lazyjj'
map global terminal-actions 'b' ':bottom-terminal<ret>'   -docstring 'bottom terminal'
map global terminal-actions 'B' ':open_blame<ret>'        -docstring 'Git Blame'
map global terminal-actions 'f' ':floating-terminal<ret>' -docstring 'Floating terminal'
map global terminal-actions 'r' ':serpl<ret>'             -docstring 'serpl'

define-command -hidden open_blame %{
  terminal-vertical tig blame %val{buffile} "+%val{cursor_line}"
}

define-command -hidden open_buffer_picker %{
  prompt buffer: -menu -buffer-completion %{
    buffer %val{text}
  }
}

define-command -hidden browse_github %{
  evaluate-commands %sh{
    gh browse "$kak_bufname:$kak_cursor_line"
 }}

# https://github.com/hadronized/config/blob/a1142ef783da4a1fd09b5d14f6f1234243304a18/kak/kakrc#L462C1-L469C2
# experiment around ! and buffer-based interactive shells
define-command -override run -shell-completion -params .. -docstring 'run command' %{
  # this is not strictly needed on every run, but it’s easier for this experiment
  set-option buffer filetype sh
  execute-keys -draft "gjo# %sh{date} %sh{pwd}<ret>"
  execute-keys -draft "gji# %arg{@}<ret>"
  execute-keys "gj!%arg{@}<ret>"
}


declare-user-mode find-actions
map global find-actions -docstring 'pick buffer'                       'B'  ':open_buffer_picker<ret>'
map global find-actions -docstring 'terminal'                          't'  ':kks-connect terminal-vertical fish<ret>'
map global find-actions -docstring 'files'                             'f'  ':kks-connect terminal-popup kks-files<ret>'
map global find-actions -docstring 'git files'                         'g'  ':kks-connect terminal-popup kks-git-files<ret>'
map global find-actions -docstring 'git changed files'                 'd'  ':kks-connect terminal-popup kks-git-changed-files<ret>'
map global find-actions -docstring 'buffers'                           'b'  ':kks-connect terminal-popup kks-buffers<ret>'
map global find-actions -docstring 'live grep(fzf)'                    'w'  ':kks-connect terminal-popup kks-grep<ret>'
map global find-actions -docstring 'live grep all files(fzf)'          'W'  ':kks-connect terminal-popup kks-grep --hidden<ret>'
map global find-actions -docstring 'browse file on github'             'B'  ':browse_github<ret>'
map global find-actions -docstring 'file types'                        'y'  ':kks-connect terminal-popup kks-filetypes<ret>'
map global find-actions -docstring 'file inside buffer basefolder'     'e'  ':basefolder-files<ret>'
map global find-actions -docstring 'file inside project root'          'E'  ':kks-connect terminal-popup kks-files-navigation<ret>'
map global find-actions -docstring 'edit file under buffer basefolder' 'p'  ':basefolder-edit<ret>'
map global find-actions -docstring 'switch themes'                     'S'  ':colorscheme<space>'
map global find-actions -docstring 'PR changed files'                  'c'  ':kks-connect terminal-popup kks-pr-diff-files<ret>'
map global find-actions -docstring 'symbols'                           's'  ':kks-connect terminal-popup kks-symbols<ret>'

define-command basefolder-files -docstring 'file inside buffer basefolder' %{
	evaluate-commands %sh{
    dir=$(dirname "$kak_bufname")
    echo "kks-connect terminal-popup kks-files-navigation \"$dir\""
	}
}

define-command basefolder-edit -docstring 'base folder edit' %{
  evaluate-commands %sh{
    dir=$(dirname "$kak_bufname")
		echo "execute-keys :e<space>$dir/"
  }
}

declare-user-mode display-actions
map global user D ':enter-user-mode display-actions<ret>' -docstring 'Enter display mode'

declare-user-mode window-actions
map global window-actions 'h' ':focus-left<ret>'  -docstring 'focus left pane'
map global window-actions 'j' ':focus-down<ret>'  -docstring 'focus down pane'
map global window-actions 'k' ':focus-up<ret>'    -docstring 'focus up pane'
map global window-actions 'l' ':focus-right<ret>' -docstring 'focus right pane'

declare-user-mode buffer-actions
map global buffer-actions '[' ':bp<ret>' -docstring 'previous buffer'
map global buffer-actions ']' ':bn<ret>' -docstring 'next buffer'
map global buffer-actions 'l' ':b<space>' -docstring 'list buffer'
map global buffer-actions '.' ':enter-user-mode buffer-actions -lock<ret>' -docstring 'Lock'

map global goto n '<esc>:bn<ret>' -docstring 'go to next buffer'
map global goto p '<esc>:bp<ret>' -docstring 'go to previous buffer'

declare-user-mode jump-actions
map -docstring 'enter jump mode (select mode: replace)' global jump-actions f ':enter_jump_mode_with_replace_select_mode<ret>'
map -docstring 'enter jump mode (select mode: extend)' global jump-actions F ':enter_jump_mode_with_extend_select_mode<ret>'
map -docstring 'enter jump mode (select mode: append)' global jump-actions <a-f> ':enter_jump_mode_with_append_select_mode<ret>'
map globa user 'j' -docstring 'Enter jump mode' ':enter-user-mode jump-actions<ret>'

map global user g ': enter-user-mode git<ret>' -docstring "git mode"
map global user T ': enter-user-mode tree-sitter<ret>' -docstring "Tree sitter mode"

# More objecct mapping from https://discuss.kakoune.com/t/useful-objects/58
map -docstring "xml tag objet" global object t %{c<lt>([\w.]+)\b[^>]*?(?<lt>!/)>,<lt>/([\w.]+)\b[^>]*?(?<lt>!/)><ret>}
map global object h 'c<gt>,<lt><ret>' -docstring "select in the (html) angle brackets"
map global object o 'c\s,\s<ret>'     -docstring "select inbetween the whitespace"

define-command glow -params .. -file-completion -docstring %{
  glow [<arguments>]: glow utility wrapper
  All optional arguments are forwarded to the glow utility
  If no arguments is passed. The current buffer will be previewed in pager mode
} %{
  evaluate-commands %sh{
    if [ $# -eq 0 ]; then
      if [ -e "$kak_buffile" ]; then
        echo "terminal-horizontal glow -p %val{buffile}"
      else
        dir="$(dirname "$kak_buffile")"
        if [ -d "$dir" ]; then
          echo "terminal-horizontal glow $dir"
        fi
      fi
    else
      echo "terminal-horizontal glow %arg{@}"
    fi
  }
}

define-command format-indent -params 0..2 -docstring '
  indentfmt [indent-type] [size]: Format current buffer indentation
  indent-type: space or tab (default: space)
  size: indentation size (number) (default: 2)
' -shell-script-candidates %{
  printf "space\ntab\n"
} %{
  evaluate-commands %sh{
    # Set defaults
    indent_type="${1:-space}"
    indent_size="${2:-2}"

    # Validate indent type
    if [ "$indent_type" != "space" ] && [ "$indent_type" != "tab" ]; then
      printf 'echo -markup {Error}Invalid indent type: must be space or tab\n'
      exit 1
    fi

    # Validate indent size is a number
    if ! [[ "$indent_size" =~ ^[0-9]+$ ]]; then
      printf 'echo -markup {Error}Invalid size: must be a positive number\n'
      exit 1
    fi

    printf '%s\n' "execute-keys '%%|indentfmt -i ${indent_type} -s ${indent_size}<ret>'"
  }
}


# Hooks
hook global RegisterModified '"' %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | pbcopy
}}

hook global WinDisplay .* %{
  focus
}

# from https://discuss.kakoune.com/t/enable-git-update-diff-automatically/1252/2
# enable flag-lines hl for git diff
hook global WinCreate .* %{
  add-highlighter window/git-diff flag-lines Default git_diff_flags
}

# from https://discord.com/channels/717163870724161556/717165513750609991/1247892374840147988
# Keep buffer list in mru order
hook global WinDisplay .* %{ arrange-buffers %val{hook_param} }

# trigger update diff if inside git dir
hook global BufOpenFile .* %{
  evaluate-commands -draft %sh{
    cd $(dirname "$kak_buffile")
    if [ $(git rev-parse --git-dir 2>/dev/null) ]; then
      for hook in WinCreate BufReload BufWritePost NormalIdle; do
        printf "hook buffer -group git-update-diff %s .* 'git update-diff'\n" "$hook"
      done
    fi
  }
}

# hook for kks mru script
hook global WinDisplay [^*].* %{
  evaluate-commands nop %sh{
    pwd="${kak_client_env_PWD}"
    mru=~/.cache/kak-mru-$(echo $pwd | sed 's|/|-|g')

    # If pwd is empty, return early
    [ -z "$pwd" ] && exit

    # Check if the mru file does not exist and create it
    [ ! -f "$mru" ] && touch "$mru"

    echo "$kak_buffile" | awk '!seen[$0]++' - "$mru" | sponge "$mru"
  }
}

hook global BufCreate .* %{
  editorconfig-load
  autoconfigtab
}

# Switch cursor color in insert mode
# ──────────────────────────────────

set-face global InsertCursor default,green+B

hook global ModeChange .*:.*:insert %{
  set-face window PrimaryCursor InsertCursor
  set-face window PrimaryCursorEol InsertCursor
}

hook global ModeChange .*:insert:.* %{
  try %{
    unset-face window PrimaryCursor
    unset-face window PrimaryCursorEol
  }
}


# Plugins

source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://github.com/jdugan6240/kak-bundle


bundle smarttab "https://github.com/andreyorst/smarttab.kak"

bundle konflict "https://github.com/eko234/git-konflict.kak" %{
  declare-user-mode konflict
  map global user k ': enter-user-mode konflict<ret>'         -docstring 'Konflict mode'
  map global konflict s ': konflict-start<ret>'               -docstring 'Konflict start'
  map global konflict j ': konflict-use-mine<ret>'            -docstring 'Use mine'
  map global konflict k ': konflict-use-yours<ret>'           -docstring 'Use yours'
  map global konflict J ': konflict-use-mine-then-yours<ret>' -docstring 'Use mine then yours'
  map global konflict K ': konflict-use-yours-then-mine<ret>' -docstring 'Use yours then mine'
  map global konflict d ': konflict-use-none<ret>'            -docstring 'Use none'
}

bundle git_mode 'https://github.com/jordan-yee/kakoune-git-mode' %{
  # Set structured commit message options here
  set-option global git_mode_use_structured_quick_commit true
  set-option global git_mode_commit_prefixes 'feat::fix::docs::refactor::build::test::style::BREAKING CHANGE::'

  # Declare git mode with default set of mappings
  # declare-git-mode

  map global git-yank 'y' ':gitlinker<ret>'           -docstring 'Copy Permalink'
}

bundle ui 'https://github.com/kkga/ui.kak' %{
  map global user u ': enter-user-mode ui<ret>' -docstring "ui mode"

  hook global WinCreate .* %{
    ui-matching-toggle
    ui-search-toggle
  }
}

bundle harpoon 'https://github.com/raiguard/kak-harpoon' %{
  declare-user-mode harpoon
  map global user o ': enter-user-mode harpoon<ret>' -docstring "Enter harpoon mode"

  map global harpoon l ':harpoon-show-list<ret>'     -docstring "List harpoon"
  map global harpoon a ':harpoon-add<ret>'           -docstring "add harpoon"

  map global harpoon 1 ':harpoon-nav 1<ret>'        -docstring "go harpoon"
  map global harpoon 2 ':harpoon-nav 2<ret>'        -docstring "go harpoon"
  map global harpoon 3 ':harpoon-nav 3<ret>'        -docstring "go harpoon"
  map global harpoon 4 ':harpoon-nav 4<ret>'        -docstring "go harpoon"
  map global harpoon 5 ':harpoon-nav 5<ret>'        -docstring "go harpoon"
  map global harpoon 6 ':harpoon-nav 6<ret>'        -docstring "go harpoon"
  map global harpoon 7 ':harpoon-nav 7<ret>'        -docstring "go harpoon"
  map global harpoon 8 ':harpoon-nav 8<ret>'        -docstring "go harpoon"
  map global harpoon 9 ':harpoon-nav 9<ret>'        -docstring "go harpoon"
}

bundle live_grep 'https://github.com/raiguard/kak-live-grep' %{
  map global find-actions -docstring 'live grep'   '/' ':live-grep<ret>'
}

bundle grep-write 'https://github.com/jtrv/grep-write.kak' %{
  map global user -docstring 'grep write' W ':grep-write<ret>'
}

bundle replace-mode https://github.com/tomKPZ/replace-mode.kak %{
  map global user r ':enter-user-mode replace<ret>' -docstring 'replace mode'
}

bundle filetree https://github.com/occivink/kakoune-filetree

bundle sshconfig https://github.com/Yukaii/ssh-config.kak

bundle case 'https://gitlab.com/FlyingWombat/case.kak.git/' %{
  map global normal ` ': enter-user-mode case<ret>'
}

# cork vue https://github.com/ABuffSeagull/kakoune-vue

bundle kak-jsts https://github.com/schemar/kak-jsts %{
  declare-user-mode format
  map global user F ':enter-user-mode format<ret>' -docstring 'Enter format mode'
  map global format p ':format-prettier<ret>'      -docstring 'Format with prettier'
  map global format e ':format-eslint<ret>'        -docstring 'Format with eslint'
}

bundle increment https://gitlab.com/Screwtapello/kakoune-inc-dec.git %{
  map global normal <c-a> ': inc-dec-modify-numbers + %val{count}<ret>' -docstring 'increment'
  map global normal <c-x> ': inc-dec-modify-numbers - %val{count}<ret>' -docstring 'decrement'
}

bundle edit-on-dir https://gitlab.com/fsub/kakoune-edit-or-dir.git/ %{
  unalias global e edit
  alias global e edit-or-dir
  set-option global edit_or_dir_hidden '-A'
}

bundle save-state https://gitlab.com/Screwtapello/kakoune-state-save.git %{
  hook global KakBegin .* %{
    state-save-reg-load colon
    state-save-reg-load pipe
    state-save-reg-load slash
  }

  hook global KakEnd .* %{
    state-save-reg-save colon
    state-save-reg-save pipe
    state-save-reg-save slash
  }

  hook global FocusOut .* %{ state-save-reg-save dquote }
  hook global FocusIn  .* %{ state-save-reg-load dquote }
}

bundle crosshair https://github.com/insipx/kak-crosshairs %{
  set-option global highlight_current_line true
  set-face   global crosshairs_line   default,rgb:383838
  set-face   global crosshairs_column default,rgb:383838

  crosshairs-change-hooks
  crosshairs-update
}

bundle Encapsul8 https://github.com/ElectricR/Encapsul8 %{
  require-module encapsul8-load-defaults
}

bundle bookmarks https://github.com/Yukaii/bookmarks.kak %{
  declare-user-mode mark
  map global user m ': enter-user-mode mark<ret>' -docstring "Enter mark mode"

  map global mark l ':bookmarks-show-list<ret>'            -docstring "List bookmarks"
  map global mark a ':bookmarks-add-prompt<ret>'           -docstring "Add bookmark"

  map global mark 1 ':bookmarks-nav 1<ret>'                -docstring "Go to bookmark"
  map global mark 2 ':bookmarks-nav 2<ret>'                -docstring "Go to bookmark"
  map global mark 3 ':bookmarks-nav 3<ret>'                -docstring "Go to bookmark"
  map global mark 4 ':bookmarks-nav 4<ret>'                -docstring "Go to bookmark"
  map global mark 5 ':bookmarks-nav 5<ret>'                -docstring "Go to bookmark"
  map global mark 6 ':bookmarks-nav 6<ret>'                -docstring "Go to bookmark"
  map global mark 7 ':bookmarks-nav 7<ret>'                -docstring "Go to bookmark"
  map global mark 8 ':bookmarks-nav 8<ret>'                -docstring "Go to bookmark"
  map global mark 9 ':bookmarks-nav 9<ret>'                -docstring "Go to bookmark"
  map global mark 0 ':bookmarks-nav 10<ret>'               -docstring "Go to bookmark"
  map global mark q ':bookmarks-nav 11<ret>'               -docstring "Go to bookmark"
  map global mark w ':bookmarks-nav 12<ret>'               -docstring "Go to bookmark"
  map global mark e ':bookmarks-nav 13<ret>'               -docstring "Go to bookmark"
  map global mark r ':bookmarks-nav 14<ret>'               -docstring "Go to bookmark"
  map global mark t ':bookmarks-nav 15<ret>'               -docstring "Go to bookmark"
  map global mark y ':bookmarks-nav 16<ret>'               -docstring "Go to bookmark"
  map global mark u ':bookmarks-nav 17<ret>'               -docstring "Go to bookmark"
  map global mark i ':bookmarks-nav 18<ret>'               -docstring "Go to bookmark"
  map global mark o ':bookmarks-nav 19<ret>'               -docstring "Go to bookmark"
  map global mark p ':bookmarks-nav 20<ret>'               -docstring "Go to bookmark"
}

bundle wrap-calculator https://github.com/Yukaii/wrap-calculator.kak %{
  map global goto J '<esc>:unset-j<ret>' -docstring 'Line move down'
  map global goto K '<esc>:unset-k<ret>' -docstring 'Line move up'
}

# bundle kakpipe "https://github.com/eburghar/kakpipe" %{
#   require-module kakpipe
# }

# bundle-install-hook kakpipe %{
# 	cargo install --force --path . --root ~/.local
# }

bundle kak-ansi https://github.com/eraserhd/kak-ansi %{
  declare-user-mode ansi-mode
  map global ansi-mode r ':ansi-render<ret>'           -docstring 'ansi-render'
  map global ansi-mode R ':ansi-render-selection<ret>' -docstring 'ansi-render-selection'
  map global ansi-mode c ':ansi-clear<ret>'            -docstring 'ansi-clear'
  map global ansi-mode e ':ansi-enable<ret>'           -docstring 'ansi-enable'
  map global ansi-mode d ':ansi-disable<ret>'          -docstring 'ansi-disable'
}

bundle-install-hook kak-ansi %{
  make
  mv kak-ansi-filter ~/.local/bin/
}
